name: Dynamic action generator

description: Takes a list of steps as YAML inside string and writes them out as a composite action

runs:
  using: node24
  main: index.js

inputs:
  steps:
    description: "A string with an array of Github Actions steps"
    required: true
  path:
    description: "The name of the folder to write the action"
    required: true
