name: Node.js test matrix generator action

description: Returns an array of Node.js major versions based on an upgrade policy and package.json

runs:
  using: node12
  main: index.js

inputs:
  upgradePolicy:
    description: "Node.js version upgrade policy. Allowed values: `lts` (default), `lts/strict`, `all`."
    default: lts
    required: false

outputs:
  matrix:
    description: "A JSON with a list of Node.js versions matching the upgrade policy, where the minimum version is the one defined in the `package.json` `engines.node` field."
  lts_latest:
    description: "Which version of node is the latest active LTS."
